services:
  backend:
    network_mode: host
    container_name: pico-weather-backend
    env_file:
      - path: backend/.env
        required: true
    build:
      context: backend
  frontend:
    network_mode: host
    container_name: pico-weather-frontend
    build:
      context: frontend